### DISCUSSION TITLE
How to use in project vapor?

### DISCUSSION THREAD

**Discussion by carlos-mayorga** [envault/envault#5] [Q&A] [answered]
How to use command **npx envault** in projects vapor?

```yml
id: id
name: name
environments:
    staging:
        memory: 1024
        cli-memory: 512
        domain: domain.dev
        storage: domain-dev
        database: my-test-database
        runtime: php-7.4
        build:
            - 'COMPOSER_MIRROR_PATH_REPOS=1 composer install'
            - 'php artisan event:cache'
            - 'npm ci && npm run dev && rm -rf node_modules'
        deploy:
            - 'npx envault envault.dev 1 Ev1VF3AH6d6QR8cw'
            - 'php artisan migrate --force'
```

view in console 
`
{"message":"Command \"npx\" is not defined.","context":{"exception":{"class":"Symfony\\Component\\Console\\Exception\\CommandNotFoundException","message":"Command \"npx\" is not defined.","code":0,"file":"/var/task/vendor/symfony/console/Application.php:644"},"aws_request_id":"b7348110-0088-42a1-8e40-72d080fea0a8"},"level":400,"level_name":"ERROR","channel":"staging","datetime":"2020-05-25T18:34:46.3511498+00:00","extra":{}}
`
